config/routes.rb
Rails.application.routes.draw do
  root to: 'statuses#index'

  resources :reports
  resources :subscribers

  scope :api do
    get 'reports_since', to: 'reports#reports_since', as: 'reports_since'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/report.rb
class Report < ApplicationRecord
  enum status: [:up, :intermittent, :down]

  after_create :update_status


  protected

  def update_status
    #Status to value map

    status_to_value = {down: -1, intermittent: 0, up: 1}

    #Number of reports to consider in score
    num_reports = 10

    #Time in which value gets linearly reduced
    time_window = 60 * 60 * 24

    #Base factor to weight scores out of the time window
    base_factor = 0.1

    now = Time.zone.now


    #Pull reports and do scoring
    recent_reports = Report.last(num_reports)

    mapped_reports = recent_reports.map do |report|
      ago = now - report.time
      weight = 1 - (ago / time_window)
      score = [base_factor, weight].max 
      score * status_to_value[report.status.to_sym]
    end

    final_score = mapped_reports.sum

    final_status = :intermittent

    if final_score >= 1
      final_status = :up
    elsif final_score <= -1
      final_status = :down
    end

    last_status = Status.last

    if last_status.nil? || (last_status && last_status.status.to_sym != final_status)
      Status.create!(status: final_status, time: DateTime.now)
    end
  end
end

app/models/status.rb
class Status < ApplicationRecord
  enum status: [:up, :intermittent, :down]
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/reports_controller.rb
#For time_ago_in_words...a bit hacky
include ActionView::Helpers::DateHelper

class ReportsController < ApplicationController

  def create
    timeout = Rails.env == "production" ? 10.minutes : 5.seconds
    #Get reports from same IP within an hour
    previous_reports = Report.where(ip: request.remote_ip, time: timeout.ago..DateTime.now)

    if previous_reports.any?
      return head :too_many_requests
    end

    if !Report.statuses.has_key? params[:report_status]
      return head :forbidden
    end

    report = Report.create(time: DateTime.now, status: params[:report_status], ip: request.remote_ip)

    if report
      return head :ok 
    end
  end


  def reports_since
    if(params[:last])
      reports = Report.where("id > #{params[:last]}")
      reports = reports.map do |report|
        {time: "#{time_ago_in_words(report.time)} ago", status: report.status.titleize, id:report.id}
      end
    else
      reports = []
    end

    render json: reports.to_json
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  def index
    @statuses = Status.order(time: :desc)
    @status = @statuses.first

    @reports = Report.order(time: :desc)
    @last_report_id = @reports.first && @reports.first.id
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  def create
    begin
      sub = Subscriber.create(:email => params[:email], :ip => request.remote_ip)

      if sub
        return head :ok
      end
    rescue
    end

    return head :bad_request
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Pokestatus'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Pokestatus'}"}
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %header
    %main{:role => "main"}
      = render 'layouts/messages'
      = render 'barq'
      = yield

app/views/statuses/index.html.haml
.container
  .row
    #status-box
      .well
        %span
          PokémonGo Server Status:
        %span#current-status-text{:class => @status.status}
          = @status.status.titleize
        %span#current-status-time
          = "Updated #{time_ago_in_words(@status.time)} ago."
  .row
    #report-box
      .well
        #report-request
          %p
            Describe the Pokémon Go server status
          = form_tag(reports_path, method: :post, remote: true, id: 'report-form') do |f|
            %button.btn.btn-success#report-up{:name => 'report_status', :value => 'up'}
              Working!
            %button.btn.btn-warning#report-intermittent{:name => 'report_status', :value => 'intermittent'}
              Intermittently working
            %button.btn.btn-danger#report-down{:name => 'report_status', :value => 'down'}
              Total Broken
        .alert.alert-success#report-thanks
          Thank you for your submission!

  .row
    .col-lg-6.col-lg-offset-3#email-box
      .well
        #email-request
          %p
            Would you like to get notifications on the server status?
          = form_tag(subscribers_path, method: :post, remote: true, class: 'form-horizontal', id: 'email-form') do
            .form-group
              = label_tag :email, "Email", class: 'col-sm-2 control-label'
              .col-sm-10
                = text_field_tag :email, nil, class: 'form-control', type: 'email'
                %p#email-disclaimer
                  We will never sell your e-mail or spam you with unrelated crap. This is just for pokemon go yo!
            .form-group
              = submit_tag 'Submit', class: 'btn btn-primary'

        .alert.alert-success#email-thanks
          Thank you for your submission!
  .row
    .col-lg-6
      #past-statuses
        .well
          %h2
            Status History
          %table.table
            %tr
              %th
                Status
              %th
                Time
            - @statuses.each do |status|
              %tr
                %td
                  = status.status.titleize
                %td
                  = "#{time_ago_in_words(status.time)} ago"

    .col-lg-6
      #reports
        .well
          %h2
            Real Time Status Reports
          %table.table#report-table
            %thead
              %tr
                %th
                  Status
                %th
                  Time
            %tbody
              - @reports.each do |report|
                %tr
                  %td
                    = report.status.titleize
                  %td
                    = "#{time_ago_in_words(report.time)} ago"

:javascript
  $(function() {
    var lastReportId = "#{@last_report_id}";

    $(document).on('ajax:complete', '#email-form', function() {
      $('#email-request').hide();
      $('#email-thanks').show();
    });

    $(document).on('ajax:complete', '#report-form', function() {
      $('#report-request').hide();
      $('#report-thanks').show();
    });

    setInterval(function(){fetchReports(lastReportId);}, 3000);

    function fetchReports(lastId) {
      $.ajax({
        'url' : "#{reports_since_path}",
        'data' : {'last' : lastId}
      }).always(function(responseData) {
        if(responseData.length > 0) {
          appendReports(responseData);
          lastReportId = responseData[responseData.length - 1].id;
        }
      });
    }

    function appendReports(reports) {
      for(var i = 0; i < reports.length; i++) {
        var report = reports[i];
        $('#report-table > tbody > tr:first').before('<tr><td>' + report.status + '</td><td>' + report.time + '</td></tr>');
      }
    }
  });